// ! Throwing Errors

try {
    throw "Error Occured in try block"
} catch (ex) {
    console.log(ex)
} finally {

}